### ISSUE TITLE
Delete / Remove a user

### ISSUE THREAD

**Issue by ichagas** [colinskow/ng-superlogin#14]
In the server side the `superlogin.removeUser()` worked OK. However, I want offer to users the option to delete their account directly from the App. This is why I need this implemented in **NG-Superlogin**

Looking on both repositories (**SuperLogin** and **NG-Superlogin**) I couldn't found a source code that make a reference to this API, any thoughts?

Thanks!

**Comment by colinskow** [comment]
This functionality is implemented in Superlogin-Demo. If you are using Angular the code is very simple...
`return $http.post('/user/destroy');`

**Comment by colinskow** [comment]
And here is the Express endpoint to accomplish the above...

``` js
app.post('/user/destroy', superlogin.requireAuth, function(req, res, next) {
  superlogin.removeUser(req.user._id, true)
    .then(function() {
      console.log('User destroyed!');
      res.status(200).json({ok: true, success: 'User: ' + req.user._id + ' destroyed.'});
    }, function(err) {
      return next(err);
    });
});
```

**Comment by ichagas** [comment]
Thanks @colinskow! It worked like a charm!

Thank you very much on the work you have done and shared, it is truly powerful.
