### ISSUE TITLE
Anyone else getting CORS issues

### ISSUE THREAD

**Issue by raymatos** [colinskow/ng-superlogin#4]
Trying to test using a remote hosted superlogin endpoint and localhost hosted app, getting the standard CORS issues. 

Not sure if you built cors into superlogin or not, so not sure if this is normal.  I fixed it in the server by adding the CORS headers.

**Comment by colinskow** [comment]
Yes, you need to manually configure CORS on CouchDB in order to use a web browser directly as a client. This is the easiest way to do it:
https://github.com/pouchdb/add-cors-to-couchdb
